### ISSUE TITLE
Get all transactions by address

### ISSUE THREAD

**Issue by tidesnetwork** [keefertaylor/TezosKit#2]
trIt would be great, if you can support getting all transactions for an account. Do you have plans on implementing this anytime soon?

**Comment by keefertaylor** [comment]
As far as I understand, a node in the network maintains balances of all contracts, but not necessarily an index of all transactions for the account. 

You'd need to build your own database or use the API for an existing one. TzScan looks like it could probably support this use case via it's API: https://tzscan.io/api#Operations%20Requests

At the moment, a second API for this stuff is probably not at the top of my mind. That being said, this does sound like a nice feature request for the future. It should be relatively easy to build:
1) Refactor network logic out of TezosClient into a super abstract class
2) Subclass the new abstract class into a TzScanClient 
3) Add RPC requests with appropriate errors and JSON response adapters 
4) Plumb these new objects through TzScanClient

Definitely more than happy to provide guidance on this work and review / merge PRs if you'd like to take a crack at it. Otherwise, I can leave this open until I have time to make forward progress on it.

**Comment by keefertaylor** [comment]
There's a few things in the TzScan API that I think make sense to include in this library. I'm mostly focused on Fornax at the moment but some of the dependent work in that project (automatically importing KT1 addresses) will probably require this sort of functionality.

**Comment by keefertaylor** [comment]
I apologize that this issue has languished for so long. 

I'm going to integrate Conseil over the next few days, which should provide this functionality.
